{{ range $.Values.dali -}}
{{- if not .disabled -}}
{{- $commonCtx := dict "root" $ "me" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: {{ .name | quote }}
      app: dali
  template:
    metadata:
      labels:
        run: {{ .name | quote }}
        app: dali
    spec:
      serviceAccountName: "hpcc-default"
      initContainers: 
        {{- include "hpcc.checkDaliMount" (dict "root" $) | indent 6 }}
      containers:
      - name: {{ .name | quote }}
        workingDir: /var/lib/HPCCSystems
        command: [ daserver ] 
        args: [
                {{ include "hpcc.configArg" . }}
              ]
{{ include "hpcc.addSentinelProbes" . | indent 8 }}
{{- include "hpcc.addSecurityContext" $commonCtx | indent 8 }}
{{- include "hpcc.addResources" (dict "me" .resources) | indent 8 }}
{{ include "hpcc.addImageAttrs" $commonCtx | indent 8 }}
        volumeMounts:
{{ include "hpcc.addConfigMapVolumeMount" . | indent 8 }}
{{ include "hpcc.addDaliVolumeMount" $commonCtx | indent 8 }}
{{ include "hpcc.addSecretVolumeMounts" (dict "root" $ "categories" (list "system" ) ) | indent 8 }}
{{- range .services -}}
{{- if not .disabled -}}
{{- $_ := set . "access" (splitList " " (include "hpcc.getSashaServiceAccess" .)) -}}
{{ include "hpcc.addSashaContainer" (dict "root" $ "me" .) | indent 6 }}
        volumeMounts:
{{- include "hpcc.addSashaVolumeMounts" (dict "root" $ "me" .) | indent 8 }}
{{- end }}
{{- end }}
      volumes:
{{ include "hpcc.addConfigMapVolume" . | indent 6 }}
{{- range .services -}}
{{- if not .disabled -}}
{{- $_ := set . "access" (without (splitList " " (include "hpcc.getSashaServiceAccess" .)) "dalidata") -}}
{{- include "hpcc.addSashaVolumes" (dict "root" $ "me" .) | indent 6 }}
{{- end }}
{{- end }}
{{ include "hpcc.addDaliVolume" $commonCtx | indent 6 }}
{{ include "hpcc.addSecretVolumes" (dict "root" $ "categories" (list "system" ) ) | indent 6 }}
{{- if or (has "data" .access) (has "dalidata" .access) -}}
{{ include "hpcc.addSecretVolumes" (dict "root" .root "categories" (list "storage" ) ) | indent 6 -}}
{{- end }}
---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .name }}-configmap 
data:
  {{ .name }}.yaml: |
    version: 1.0
    dali:
{{ toYaml (omit . "logging" "services") | indent 6 }}
{{- include "hpcc.generateLoggingConfig" $commonCtx | indent 6 }}
{{ include "hpcc.generateVaultConfig" (dict "root" $ "categories" (list "system" ) ) | indent 6 }}
    global:
{{ include "hpcc.generateGlobalConfigMap" $ | indent 6 }}
---
{{- $daliScope := . -}}
{{- range .services -}}
{{- if not .disabled -}}
{{- $_ := set . "access" (splitList " " (include "hpcc.getSashaServiceAccess" .)) -}}
kind: ConfigMap
{{- with (. | merge (pick $daliScope "logging")) }}
{{ include "hpcc.sashaConfigMap" (dict "root" $ "me" .) }}
{{- end }}
---
{{- if .servicePort -}}
{{ include "hpcc.addSashaService" (dict "root" $ "me" .) }}
---
{{- end }}

{{- if .storage }}
{{- if (not .storage.existingClaim) }}
{{ include "hpcc.addPVC" (dict "root" $ "name" (printf "sasha-%s" .service) "me" .storage) }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name | quote }}
spec:
  ports:
  - port: 7070
    protocol: TCP
    targetPort: 7070
  selector:
    run: {{ .name | quote }}
  type: ClusterIP
---
{{- if (not $.Values.storage.daliStorage.existingClaim) }}
{{- $storage := ($.Values.storage | default dict) -}}
{{- $daliStorage := ($storage.daliStorage | default dict) -}}
{{- $modeForCoalescer := (has "coalescer" .services) | ternary "ReadWriteOnce" "ReadWriteMany" -}}
{{- include "hpcc.addPVC" (dict "root" $ "name" "dalistorage-pvc" "mode" $modeForCoalescer "me" $daliStorage) -}}
{{- end }}
{{- end }}
{{- end }}
