{{- $storage := (.Values.storage | default dict) -}}
{{- $dataStorage := ($storage.dataStorage | default dict) -}}
{{- if (not $dataStorage.existingClaim) }}
{{ include "hpcc.addPVC" (dict "root" $ "name" "datastorage-pvc" "me" $dataStorage) }}
{{- end }}
