{{- $storage := (.Values.storage | default dict) -}}
{{- $dllStorage := ($storage.dllStorage | default dict) -}}
{{- if (not $dllStorage.existingClaim) }}
{{ include "hpcc.addPVC" (dict "root" $ "name" "dllstorage-pvc" "me" $dllStorage) }}
{{- end }}
