apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "dali-%s-pv" (include "hpcc-localfile.fullname" $) }}
  labels:
    store: {{ printf "dali-%s-pv" (include "hpcc-localfile.fullname" $) }}
spec:
  storageClassName: "manual"
  capacity:
    storage: {{ .Values.daliStorage.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    type: Directory
    path: {{ .Values.daliStorage.hostpath | default (printf "%s/dali" .Values.common.hostpath) | required "Please specify hostpath" | quote }}
