apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "dali-%s-pvc" (include "hpcc-localfile.fullname" $) }}
spec:
  storageClassName: "manual"
  volumeName: {{ printf "dali-%s-pv" (include "hpcc-localfile.fullname" $) }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.daliStorage.size }}
  selector:
    matchLabels:
      store: {{ printf "dali-%s-pv" (include "hpcc-localfile.fullname" $) }}
