apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "dll-%s-pv" (include "hpcc-localfile.fullname" $) }}
  labels:
    store: {{ printf "dll-%s-pv" (include "hpcc-localfile.fullname" $) }}
spec:
  storageClassName: "manual"
  capacity:
    storage: {{ .Values.dllStorage.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    type: Directory
    path: {{ .Values.dllStorage.hostpath | default (printf "%s/dlls" .Values.common.hostpath) | required "Please specify hostpath" | quote }}
