# Default values for hpcc.

global:
  # Settings in the global section apply to all HPCC components in all subcharts
  
  dllserver:
    storageSize: 3Gi

  image:
    # This should probably say "latest" or "stable" in the example script, but set to a specific version in production systems
    # We should also support overriding the version within a component
    version: master-2020-02-10
    root: "hpccsystems"    # change this if you want to pull your images from somewhere other than DockerHub hpccsystems/*
    pullPolicy: IfNotPresent

  # Remove or override this if you don't want the simplified assumptions (including
  # persistent storage that is local to the node) used for single-node installations
  
  singleNode: true

dali:
- name: mydali

eclagent:
- name: myeclagent
  replicas: 1
    
eclccserver:
- name: myeclccserver
  replicas: 1
    
esp:
- name: myesp
  replicas: 1

notroxie:
  - name: roxie1
    ports: [ 9876, 0 ]
    localSlave: 1
    Xconfig: |
     {
      "array": [
        1,
        2,
        3
      ],
      "boolean": true,
      "number": 123,
      "object": {
        "a": "b",
        "c": "d",
        "e": "f"
      },
      "string": "Hello World"
     }
    
roxie:
  - name: roxie2
    ports: [ 9876, 0 ]
    numChannels: 2
    topoport: 9004
    XconfigFile: "roxie.yaml"
   
notroxie: 
  - name: roxie3
    ports: 9876
    numChannels: 2
    serverReplicas: 1
    topoReplicas: 2
    topoport: 9004
    Xconfig: |
      hello there


    