{{ range $.Values.eclagent -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name | quote }}
spec:
  replicas: {{ .replicas | default 1 }}
  selector:
    matchLabels:
      run: {{ .name | quote }}
  template:
    metadata:
      labels:
        run: {{ .name | quote }}
    spec:
      containers:
      - name: {{ .name | quote }}
        args: [ 
                {{ include "hpcc.utils.configArg" . }},
                {{ include "hpcc.utils.daliArg" $ }}
              ]
{{ include "hpcc.utils.addImageAttrs" (dict "root" $ "imagename" "eclagent") | indent 8 }}
{{ include "hpcc.utils.addVolumeMounts" . | indent 8 }}
{{ include "hpcc.utils.addVolumes" . | indent 6 }}
---
{{- include "hpcc.utils.generateConfigMap" (dict "root" $ "me" .) -}}
---
{{- end }}
